FROM mcr.microsoft.com/dotnet/sdk:6.0
RUN mkdir /app

WORKDIR /app
COPY mvc1.csproj .

RUN dotnet restore
COPY . .

# Aqui, especificamos o arquivo .csproj ao invés de apenas rodar o dotnet publish
RUN dotnet publish mvc1.csproj -c Release -o dist

EXPOSE 80/tcp
ENTRYPOINT ["dotnet", "dist/mvc1.dll"]
